apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: conversation
  rules:
    - actions: ["create","view"]
      roles:
        - agency-profile-admin
        - individual-admin
        - employer-admin
      effect: EFFECT_ALLOW
    - actions: [ "reply" ]
      roles:
        - agency-profile-admin
        - individual-admin
        - employer-admin
        - individual-user
        - employer-user
      effect: EFFECT_ALLOW

