apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: individual_user_link
  rules:
    - actions: ["view"]
      roles:
        - agency-profile-admin
        - individual-admin
        - individual-user
      effect: EFFECT_ALLOW
    - actions: [ "update","delete" ]
      roles:
        - agency-profile-admin
        - individual-admin
      effect: EFFECT_ALLOW
    - actions: ["create"]
      roles:
        - agency-profile-admin
      effect: EFFECT_ALLOW