apiVersion: api.cerbos.dev/v1
resourcePolicy:
  version: "default"
  resource: record
  rules:
    - actions: [ "create" ]
      roles:
        - record-submitter
        - record-admin
      effect: EFFECT_ALLOW

    - actions: [ "view" ]
      roles:
        - record-submitter
        - record-admin
      effect: EFFECT_ALLOW

    - actions: [ "update" ]
      roles:
        - record-admin
      effect: EFFECT_ALLOW

    - actions: [ "update-admin-data" ]
      roles:
        - record-admin
      effect: EFFECT_ALLOW